version: '3'

services:
  db:
    image: mongo
    container_name: dbmongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
  
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DB_PORT=db
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    links:
      - db
  
  frontend:
    # build: ./frontend
    image: miova2807/fsa
    container_name: frontend_sa
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - backend
  
volumes:
  mongo-data:
    